name: Step Types

on: 
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - run : echo "inline bash script"

  second-job:
    runs-on: ubuntu-24.04
    steps:
      - run: print ("using python script")
        shell: python
  
  third-job: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
        with:
          who-to-greet: 'JavaScript Action from the Marketplace'